### ISSUE TITLE
Question about the meta-test.

### ISSUE THREAD

**Issue by z1358** [yinboc/few-shot-meta-baseline#33]
Dear author,
I have some questions about the meta-test stage.
In your paper, you apply `consistent sampling` and `the same 800 testing tasks are sampled for estimating the performence`. But in the `test_few_shot.py`, I find the random seed is fixed as `0` and the default value of the parameter `test-epochs` is `10`. Do you mean runing the same 800 testing tasks for ten times and computing the average acc?
If so, since the meta-test stage is non-parametric, why different test-epochs get different acc?
Looking forward to your reply！

**Comment by MohamedAfham** [comment]
Hi, 
I have the same question as @z1358. Can you please let me know, 
1. Why multiple testing epochs are used during meta-testing stage?
2. Since the seed is set to be 0 _(np.random.seed(0))_,  why different test-epochs get different acc ?
3. For each test-epoch, we get average accuracy with std. How is the final accuracy reported in the paper calculated from the set of test_epochs?

Looking forward to hear from you!

**Comment by flcaus** [comment]
Hi，
I have the same question @z1358 @MohamedAfham ，have you solved it?
